#! /usr/bin/env python

import sys
import os
from itertools import chain

from subprocess import check_output

python_files = chain.from_iterable(
    [os.path.join(root, fname) for fname in fnames if fname.endswith('.py')]
    for root, dirs, fnames in os.walk('txwinrm')
)

command = ['cyclic_complexity/pygenie.py', 'complexity']
command.extend(python_files)
output = check_output(command)

exit_code = 0
for line in output.splitlines():
    line = line.strip()
    if not line:
        continue
    print line
    if line.startswith('File:') \
            or line == "This code looks all good!":
        continue
    exit_code = 1

sys.exit(exit_code)
