#! /usr/bin/env python

import sys
from subprocess import check_output

output = check_output([
    'cyclic_complexity/pygenie.py',
    'complexity',
    'txwinrm/enumerate.py',
    'txwinrm/shell.py',
    'txwinrm/util.py',
    'txwinrm/winrm.py',
    'txwinrm/winrs.py',
    'txwinrm/collect.py',
    'txwinrm/constants.py',
    'txwinrm/__init__.py'])

exit_code = 0
for line in output.splitlines():
    line = line.strip()
    if not line:
        continue
    print line
    if line.startswith('File:') \
            or line == "This code looks all good!":
        continue
    exit_code = 1

sys.exit(exit_code)
