#! /bin/sh

##############################################################################
#
# Copyright (C) Zenoss, Inc. 2013, all rights reserved.
#
# This content is made available according to terms specified in the LICENSE
# file at the top-level directory of this package.
#
##############################################################################

set -u

coverage run --source=txwinrm.$1 `which trial` txwinrm/test/test_$1.py
coverage report -m
